language: python
python:
    - "3.6"
script:
    - python -m unittest discover
before_install:
    - pip install coverage
    - pip install codecov
after_success:
    - coverage run --branch test/test_*.py
    - codecov 
